### ISSUE TITLE
Resize multiple notes at once

### ISSUE THREAD

**Issue by EntrianAudio** [EntrianAudio/Rack#37]
You should be able to drag-select a group of notes and adjust their lengths with one gesture.

(Suggestion from @Coirt.)

**Comment by mysterybear** [comment]
Absolutely...

Honestly a little peeved as a purchaser... This is a totally standard MIDI editing interaction isn't it?

Edit: sorry, maybe "peeved" is a bit ambiguous. What I mean is, this feature would've fell into my expectations pre-purchase and I'm surprised it's not in. It's also the kind of thing that's like... It's going to be easier for me to MIDI-edit in Ardour and then import the MIDI file into Entrian because of this, whereas if this feature was in then that wouldn't be the case... So it's a big deal for me... Hope that's more useful feedback than "peeved" lol

**Comment by RichieHindle** [comment]
To be honest, "peeved" was totally reasonable.  :-)  This is something you'd expect to find in a product like this.  I'll try to get it into the next release.

**Comment by RichieHindle** [comment]
Implemented in version 2.2.0 - sorry it's taken so long...
