### ISSUE TITLE
Arming a track without using the mouse (timeline)

### ISSUE THREAD

**Issue by ghost** [EntrianAudio/Rack#50]
I love this sequencer and it would be great to be able select the track without the mouse. Something that could be midi mapped or driven by cv. Thanks, H

**Comment by RichieHindle** [comment]
Thanks for the suggestion!  I'll have a think about how it might be done, and come back with a proposed design.

**Comment by RichieHindle** [comment]
Would this give you what you're asking for?:

The list of tracks on the Timeline module's screen (or channels on the CV module's screen) becomes a parameter that you can map to a knob on a MIDI controller using the MIDI-MAP module.  You click on a slot in MIDI-MAP, wiggle the knob, click anywhere in the track list, and the mapping is created.

The full range of the knob is mapped to the 10 tracks, so hard left arms track 1 and hard right arms track 10.

You can use Stoermelder's CV-MAP or µMAP to map a CV signal rather than MIDI, which will map either the unipolar voltage range from 0V to 10V, or the bipolar range from -5V to 5V, to the range of tracks or channels.

So selecting with a knob on your MIDI device is easy, and using CV is easy.

To select with a note on a MIDI keyboard, feed the keyboard through MIDI-CV and a ConstAddMult that's set up to scale the notes up from the small range around Middle C to the full bipolar range, then into a bipolar µMAP, and the notes around Middle C will select the tracks/channels.

To select with a MIDI pad, set everything up as though for a MIDI keyboard and set the pad to send the appropriate note.

I think that covers all the ways you might want to select a track?

Limitations:

Timeline only allows one armed track at once, but the CV module allows multiple channels to be armed by connecting a poly cable to the Record input.  Using this feature, you could only arm one CV channel at once.  The presence of a poly cable on CV's Record input would disable this feature.

There would be no way to control which CV channels within a Timeline song were armed for recording.  (You can work around that limitation by recording into a CV module and then copy/pasting the recording into your Timeline song afterwards.)

**Comment by ghost** [comment]
That sounds fantastic, covers all the functionality I was thinking of!

**Comment by RichieHindle** [comment]
Great!  I'll see what I can do for the next release.

**Comment by RichieHindle** [comment]
Implemented in 1.1.18 - let me know whether it does what you wanted!

**Comment by ghost** [comment]
sorry for the late reply - everything works great. I did notice that the module doesn't display changes in arming tracks when it's not running, but this has no effect on the functionality. Thanks so much for running with my suggestion, love this module and being able to control it all from a keyboard makes it awesome for live performance

**Comment by RichieHindle** [comment]
Great!  Thanks for letting me know.

(Good spot with "doesn't display changes in arming tracks when it's not running" - that's fixed for the next release. )
