### ISSUE TITLE
Triggering Entrian Drummer patterns with Entrian Timeline problem

### ISSUE THREAD

**Issue by spectromas** [EntrianAudio/Rack#76]
I asked about this [on the forum](url/https://community.vcvrack.com/t/got-a-strange-problem-triggering-entrian-drummer-patterns-with-entrian-timeline/13416) first and so far it looks like this is at least reproducible but it still could be user error. 

Basically when I trigger phrases of the Drummer from Timeline the beat is not played as it should. I noticed this by inserting a blank pattern for one bar. The result was that a kick is played on the first beat of the blank bar and the kick is missed from the following bar.

**Comment by RichieHindle** [comment]
This was a combination of a bug and a gotcha.

The bug is now fixed, and dealing with the gotcha is now much simpler.

The gotcha is the fact that Rack cables come with a one-sample delay, so if you feed the same clock to both a scene sequencer and a trigger sequencer, the change of scene will arrive one sample too late to affect the first beat of a scene.

The fix is to add a one-sample delay to the trigger sequencer’s clock input, and this is now easy: there’s a “Delay Clock” menu, which lets you control the clock delay without needing to use a separate delay module.  And what’s more, that menu has an “Auto” option, enabled by default, which makes the most common cases just work without needing to do anything.

![image](https://user-images.githubusercontent.com/4448057/119313747-cf472180-bc6b-11eb-9d86-01e0ae951d35.png)

The bug was that the clock needed to be delayed by lots of samples, not just one, in order to make things work.  That's now fixed, but less relevant since the clock delay is now built-in and in most cases automatic.
